import tkinter
from tkinter import *
from tkinter import ttk

window = tkinter.Tk()
window.geometry("500x500")

label_judul = Label(window, text="Sending of Message Form")
label_judul.place(x=130,y=10)
label_setiing = Label(window, text="Settings")
label_setiing.place(x = 60, y= 60)
kotak_setiing = Frame(window,bg="gray",height=80, width=260)
kotak_setiing.place(x= 60, y = 80)
teks_mode = Label(window, text="Mode : ",bg="gray")
teks_mode.place(x= 60,y=90)
mode = ttk.Combobox(window,width=4)
mode.place(x=115, y = 90)
subject_teks = Label(window, text="Subject : ",bg="gray")
subject_teks.place(x= 60, y=125)
subject = ttk.Combobox(window, width=4)
subject.place(x=115,y=125)
teks_koneksi = Label(window, text="Connection : ",bg="gray")
teks_koneksi.place(x= 160, y = 90)
connection = ttk.Combobox(window,width=4)
connection.place(x=240, y = 90)
teks_remote = Label(window, text="Remote IP : ",bg="gray")
teks_remote.place(x = 160, y = 125)
remote = Entry(window,width=7)
remote.place(x=240, y = 125)
centang = Button(window, text="ya")
centang.place(x=290, y = 125)

teks_sender = Label(window, text="Sender")
teks_sender.place(x=30,y = 170)
sender = Frame(window,bg="gray", height=290, width=150)
sender.place(x= 20, y= 190)
teks_nomes = Label(window, text="No.Mes:",bg="gray")
teks_nomes.place(x=20, y=195)
nomes = ttk.Combobox(window, width=10)
nomes.place(x= 75,y= 195)
teks_name = Label(window, text="Name:",bg="gray")
teks_name.place(x=20,y=225)
name = Entry(window, width=13)
name.place(x= 75,y= 225)
teks_subject = Label(window, text="Subject:",bg="gray")
teks_subject.place(x=20,y=255)
subject_entry = Entry(window, width=13)
subject_entry.place(x= 75,y= 255)
teks_content = Label(window,text="Contents:",bg="gray")
teks_content.place(x=20, y =280)
kotak_content = Frame(window, bg="white",width=100, height=80)
kotak_content.place(x=40,y= 305)
scale1 = Scale(length=74).place(x= 110,y=305)

window.mainloop()
